# Generated by Django 5.2.7 on 2025-11-05 08:12

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', validators=[posts.models.validate_userrequest_image_extension]),
        ),
    ]
