# Generated by Django 5.2.7 on 2025-11-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='UserRequest',
        ),
    ]
