# Generated by Django 5.2.7 on 2025-11-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_request_userrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
