# Generated by Django 5.2.7 on 2025-11-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_userrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='status',
            field=models.CharField(choices=[('n', 'Новая заявка'), ('a', 'Принято в работу'), ('d', 'Выполнено')], default='n', max_length=1),
        ),
    ]
