# Generated by Django 5.2.7 on 2025-11-04 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_userrequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
