# Generated by Django 5.2.7 on 2025-11-04 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_userrequest_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
