# Generated by Django 5.2.7 on 2025-11-04 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_userrequest_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
        ),
    ]
